### ISSUE TITLE
getroom is returning bad json

### ISSUE THREAD

**Issue by zimmer62** [espenhogbakk/homeseer-jsonapi#1]
The ShowRoom method leave a comma after each itteration.  Trying to parse this json data from Jquery it fails due to the json not following strict standards.

I fixed it in my local copy by only adding the commas before the ShowDevice(id) call only if it's not the first time through the iteration.

**Comment by espenhogbakk** [comment]
That was quick, only published this last night, and you're already using it, awesome. I noticed this issue as well, haven't gotten around to fixing it myself. Please submit a github pull request, and I'll pull it in.

**Comment by TheInsomniac** [comment]
The fix is quite simple for both the getroom and getdevices. There is an extra ',' at the end of the last device making the JSON invalid. If you place an if statement in the response.write of each function so that it reads:

```
if not devices.Finished then
  response.write ", "
```

   end if

Then the last element will not have a , appended to it fixing this issue.

The one other issue with getdevices is that Housecodes and strings can contain "\" which require escaping thereby breaking the JSON. 

A simple Replace(device.name, "\", "\u005C"), and Replace(id, "\", "\u005C") fixes THIS issue.

**Comment by espenhogbakk** [comment]
Closed after the awesome @manxam contributed with this PR: https://github.com/espenhogbakk/homeseer-jsonapi/pull/3
